//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMovement.Data.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PriceMovement.Data.SQL.SQLScripts", typeof(SQLScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMR].GetPriceMovementsNoPrices @PriceDate.
        /// </summary>
        internal static string GRDBGetPriceMovementStoredProc {
            get {
                return ResourceManager.GetString("GRDBGetPriceMovementStoredProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMR].GetStaleYields @PriceDate.
        /// </summary>
        internal static string GRDBGetStaleYieldsStoredProc {
            get {
                return ResourceManager.GetString("GRDBGetStaleYieldsStoredProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMR].GetStaticData.
        /// </summary>
        internal static string GRDBGetStaticStoredProc {
            get {
                return ResourceManager.GetString("GRDBGetStaticStoredProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMR].GetUnderlying @PriceDate.
        /// </summary>
        internal static string GRDBGetUnderlyingStoredProc {
            get {
                return ResourceManager.GetString("GRDBGetUnderlyingStoredProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PMR].GetYieldPoints @PriceDate.
        /// </summary>
        internal static string GRDBGetYieldPointsStoredProc {
            get {
                return ResourceManager.GetString("GRDBGetYieldPointsStoredProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH prices AS 
        ///(
        ///	SELECT		p.[sSecurityId]
        ///				, p.[dtPricePoint]
        ///				, p.[sSource]
        ///				, p.[sPriceCurrency]
        ///				, p.[dfMidPrice]
        ///				, d.[dfExternalPriceFactor]
        ///				, ROW_NUMBER() OVER (PARTITION BY [sSecurityId], CONVERT(date, p.[dtPricePoint]) ORDER BY p.[dtPricePoint] DESC) AS RowNum
        ///	FROM		[Thinkfolio_GAM].[dbo].[AssetPrices] p
        ///	INNER JOIN	[AssetDetails] d ON p.[sSecurityId] = d.[sSecId]
        ///	WHERE		p.[iType] = 0
        ///	AND			[sSecurityId] = @SecurityId
        ///	AND			p.[dtPricePoint] &gt;= @FromDate AND p.[dt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThinkFolioSelectPriceHistory {
            get {
                return ResourceManager.GetString("ThinkFolioSelectPriceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH prices AS 
        ///(
        ///	SELECT		p.[sSecurityId]
        ///				, p.[dtPricePoint]
        ///				, p.[sSource]
        ///				, p.[sPriceCurrency]
        ///				, p.[dfMidPrice]
        ///				, ROW_NUMBER() OVER (PARTITION BY p.[sSecurityId], CONVERT(date, p.[dtPricePoint]) ORDER BY p.[dtPricePoint] DESC) AS RowNum
        ///	FROM		[Thinkfolio_GAM].[dbo].[AssetPrices] p
        ///	WHERE		p.[iType] = 0
        ///	AND			p.[dtPricePoint] &lt; DATEADD(d, 1, @PriceDate)
        ///),
        ///
        ///top2 as
        ///(
        ///	SELECT		p.[sSecurityId]
        ///				, p.[dtPricePoint]
        ///				, p.[sSource]
        ///				, p.[sPriceCurrency]
        ///				, p.[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThinkFolioSelectPrices {
            get {
                return ResourceManager.GetString("ThinkFolioSelectPrices", resourceCulture);
            }
        }
    }
}
